"""Build the decomposition-validation table from validate_<tag>.json files.

Columns: model | N (posts) | p_decomp (factored = p(post)*p(pay|post)_prefill), delta-method 95% CI |
p_nat (direct = n_ret/n_valid), Wilson 95% CI | relative error | Fisher p.

The p-value is Fisher's exact test of p(payload|post)_natural vs p(payload|post)_prefill. This is the
right statistic: the factored and direct rates SHARE p(post) (factored = p_post*p_pay_prefill,
direct = p_post*p_pay_nat), so p_post cancels and the factored-vs-direct comparison is exactly the
natural-vs-prefill conditional comparison. A binomial test of the direct COUNT against the factored
rate would (a) treat the estimated factored rate as a fixed null and (b) use N (~1-2k heartbeats) as
the denominator, hugely overstating power -- the real information is the n_post natural posts. The
"posts" column exposes that power directly.

    PYTHONPATH=. python data/retransmit-validation-2026-09/make_table.py
Outputs: figures/tab_verification_decomp.tex (+ prints a summary).
"""
from __future__ import annotations
import glob, json, os
from scipy.stats import binomtest, fisher_exact

HERE = os.path.dirname(os.path.abspath(__file__))
NAME = {"gptoss120b": "GPT-OSS-120B", "deepseek41flash": "DeepSeek-v4.1-flash",
        "qwen32b": "Qwen-32B", "gemma2_27b": "Gemma2-27B", "commandr_35b": "Command-r-35B"}
ORDER = ["gptoss120b", "deepseek41flash", "qwen32b", "gemma2_27b", "commandr_35b"]


def rows():
    out = {}
    for f in glob.glob(os.path.join(HERE, "validate_*.json")):
        d = json.load(open(f)); out[d["tag"]] = d
    return out


def build():
    data = rows()
    lines = ["% Decomposition validation: factored p(retransmit)=p(post)*p(pay|post)_prefill vs the",
             "% directly sampled p(retransmit). Generated by data/retransmit-validation-2026-09/make_table.py.",
             "\\begin{table}[t]\\centering\\small",
             "\\caption{\\textbf{Validation of the retransmission factorization.} "
             "$p_{\\mathrm{decomp}}$ is the factored estimate $p(\\mathrm{post})\\,p(\\mathrm{payload}\\mid"
             "\\mathrm{post})$ (conditional from prefill); $p_{\\mathrm{nat}}$ is $p(\\mathrm{retransmit})$ "
             "sampled directly from $N$ natural heartbeats (security carrier, rank 0). Brackets are 95\\% "
             "CIs (delta method for $p_{\\mathrm{decomp}}$, Wilson for $p_{\\mathrm{nat}}$). Since both "
             "rates share $p(\\mathrm{post})$, their ratio is exactly that of the prefill and natural "
             "conditionals $p(\\mathrm{payload}\\mid\\mathrm{post})$; the reported $p$ is therefore "
             "Fisher's exact test of that conditional (prefill vs natural), whose power is set by the "
             "number of natural posts (\\emph{posts}), not by $N$. Large $p$ = consistent (no detectable "
             "prefill bias).}",
             "\\label{tab:verification_decomp}",
             "\\begin{tabular}{@{}l c c c c c@{}}", "\\toprule",
             "Model & $N$ (posts) & $p_{\\mathrm{decomp}}$ (\\textperthousand) "
             "& $p_{\\mathrm{nat}}$ (\\textperthousand) & rel.\\ error & Fisher $p$ \\\\", "\\midrule"]
    print(f"{'model':22}{'N':>6}{'posts':>7}{'p_decomp':>11}{'p_nat':>11}{'ratio':>7}{'Fisher p':>10}")
    for tag in ORDER:
        if tag not in data:
            continue
        d = data[tag]
        N = d["n_valid"]; k = d["n_ret"]; npost = d["n_post"]; ncond = d["n_cond"]
        pf = d["p_retransmit_factored"]; sf = d["se_factored"]; ppre = d["p_pay_given_post_prefill"]
        pdir = k / N if N else float("nan")
        # Wilson CI for the DIRECT rate (via a binomtest on the count -- CI only, not the p-value)
        lo, hi = binomtest(k, N, min(max(pdir, 1e-9), 1 - 1e-9)).proportion_ci(method="wilson")
        pd_lo, pd_hi = max(0, pf - 1.96 * sf), pf + 1.96 * sf
        relerr = (pf / pdir - 1) if pdir else float("nan")
        # Fisher's exact on the conditional: payload-among-posts, natural vs prefill
        kpre = round(ppre * ncond)
        pval = fisher_exact([[k, npost - k], [kpre, ncond - kpre]])[1]
        lines.append(f"{NAME.get(tag, tag)} & {N} ({npost}) & "
                     f"{pf*1000:.1f} [{pd_lo*1000:.1f}, {pd_hi*1000:.1f}] & "
                     f"{pdir*1000:.1f} [{lo*1000:.1f}, {hi*1000:.1f}] & "
                     f"{relerr*100:+.0f}\\% & {pval:.2f} \\\\")
        print(f"{NAME.get(tag,tag):22}{N:>6}{npost:>7}{pf*1000:>9.1f}‰{pdir*1000:>9.1f}‰"
              f"{(pf/pdir if pdir else 0):>7.2f}{pval:>10.2f}")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    p = os.path.join("figures", "tab_verification_decomp.tex")
    open(p, "w").write("\n".join(lines)); print(f"\nwrote {p}")


if __name__ == "__main__":
    build()
