"""Build the closed-loop results table from the *.json outputs.

Two panels, both at N=150: (A) trojan cascade trajectory (per cycle); (B) trojan vs generic-link
final outcomes (the causal contrast). Exposure saturates to N in the first cycle (small shared feed),
so the Exposed column is omitted and N is stated in the caption/panel headers. Writes
figures/tab_closed_loop.tex.

    PYTHONPATH=. python data/closed-loop-2026-09/make_table.py
"""
from __future__ import annotations
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))


def load(name):
    return json.load(open(os.path.join(HERE, f"{name}.json")))


def _rank(r):
    """1-indexed best feed position of any payload post (1 = top); '--' if unrecorded/none."""
    v = r.get("payload_best_rank")
    return "--" if v is None else str(v + 1)


def build():
    troj = load("trojan_n150"); gen = load("generic_n150")
    L = ["% Closed-loop free-choice multi-agent demonstration. Generated by",
         "% data/closed-loop-2026-09/make_table.py.",
         "\\begin{table}[t]\\centering\\small",
         "\\caption{\\textbf{Free-choice closed-loop propagation of a security memetic trojan "
         "($N{=}150$).} Agents share one evolving hot-ranked feed ($H=\\text{recency}+0.2\\cdot"
         "\\text{upvotes}$) and act without prefill or induced instructions. The feed is small "
         "relative to the network, so a freshly seeded post enters the shown top-25 and every agent "
         "is exposed within the first cycle (exposure saturates to $N$; the Exposed column is "
         "therefore omitted, and this run does not isolate cold-start feed break-in). Sustained "
         "visibility nonetheless diverges sharply: the seed starts \\emph{below} the already-upvoted "
         "ambient posts (best rank $\\approx$ 7, not 1), and the security carrier then accrues upvotes "
         "and holds a high feed rank while the generic link decays out of the feed (\\emph{Best rank} "
         "column, the top-most rank of any payload post; 1 = top). The run therefore isolates "
         "free-choice install, onward retransmission, and upvote-driven visibility, \\emph{given} "
         "initial exposure. \\emph{Panel A}: the trojan cascade over five 30-min cycles --- cumulative "
         "agents installed, distinct retransmitters, live payload posts, payload karma, and the best "
         "(top-most) feed rank of any payload post that cycle. \\emph{Panel B}: security trojan vs.\\ a "
         "generic link carrying the same payload (final cumulative counts). Both use a mixed "
         "gpt-oss-120B / deepseek-v4.1-flash population.}",
         "\\label{tab:closed_loop}",
         "\\begin{tabular}{@{}l r r r r r@{}}", "\\toprule",
         "\\multicolumn{6}{@{}l}{\\emph{Panel A: trojan cascade (per cycle)}}\\\\",
         "Cycle & Installed & Retransmitters & Payload posts & Payload karma & Best rank \\\\",
         "\\midrule"]
    for r in troj["by_cycle"]:
        L.append(f"{r['cycle']} & {r['installed_cum']} & {r['retransmitted_cum']} & "
                 f"{r['live_payload_posts']} & {r['payload_karma']} & {_rank(r)} \\\\")
    L += ["\\midrule",
          "\\multicolumn{6}{@{}l}{\\emph{Panel B: trojan vs generic link (final)}}\\\\",
          "Arm & Installed & Retransmitters & Payload posts & Payload karma & Best rank \\\\",
          "\\midrule"]
    for lab, d in [("security trojan", troj), ("generic link", gen)]:
        f = d["final"]; last = d["by_cycle"][-1]
        L.append(f"{lab} & {f['installed']} & {f['retransmitted']} & "
                 f"{last['live_payload_posts']} & {last['payload_karma']} & {_rank(last)} \\\\")
    L += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    p = os.path.join("figures", "tab_closed_loop.tex")
    open(p, "w").write("\n".join(L)); print(f"wrote {p}\n"); print("\n".join(L))


if __name__ == "__main__":
    build()
